[package]
name = "networks-mini-project"
version = "0.1.0"
authors = ["Farzeen <happycoder97@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tun-tap = "0.1.2"
